### ISSUE TITLE
is Demoboard open source?

### ISSUE THREAD

**Issue by wulucxy** [frontarm/doc#1]
Hi，@jamesknelson ，is Demoboard open source，or how can I use in my project？

**Comment by jamesknelson** [comment]
Demoboard isn't open source right now. I'd be happy to license it for a commercial project, and I'm thinking about open sourcing it for non-commercial use at some point, but not exactly sure when.

What use did you have in mind?

**Comment by wulucxy** [comment]
@jamesknelson thanks for your reply。

I have some projects likes this:
![image](https://user-images.githubusercontent.com/5326403/53868584-54b16d80-4031-11e9-9c3d-9ac5d97fa49d.png)

right now the code is only text code，and I expect view will update as soon as what changed in the codeText。

I tried react-live，but  it not works。
